"""
GRSD-Reflect Trainer: POLICY-NATIVE two-stage skill construction.

Subclasses GRSDRayTrainer. The ONLY difference from the original GRSD is HOW the
privileged prior z_x is produced and that the reflection itself becomes a
trainable object:

  Original GRSD (grsd_ray_trainer.py, UNTOUCHED):
      * Stage A (per-trajectory reflection) and Stage B (contrastive prior) are
        both produced by an EXTERNAL API LLM (SkillReflector). Nothing trainable.

  GRSD-Reflect (this file):
      * Stage A  s_i ~ pi_theta(. | x, tau_i, R_i, p_ref) is generated by the
        POLICY's own rollout engine and is TRAINABLE. Its reward is a discrete
        rubric score r^ref_i in {0,1,2,3} from an external ReflectionJudge, turned
        into A^ref_i = Norm_G(r^ref_i). The reflection tokens receive their own
        GRPO update, added with a small coefficient alpha (paper: L = L_task +
        alpha * L_ref).
      * Stage B  z_x ~ pi_{bar theta}(. | x, S+, S-, p_prior) is generated by a
        STOP-GRADIENT snapshot of the policy (the same rollout/inference engine,
        under no_grad), so no gradient flows through z_x. It is used only as the
        teacher's privileged text context, exactly like the original GRSD prior.

Everything downstream of z_x (teacher forward, turn-level advantage modulation,
task update) is inherited unchanged from GRSDRayTrainer. The reflection update is
performed as a SEPARATE optimizer pass (update_reflect_actor) because the
reflection sequences are entirely different token sequences from the task
trajectory rows and cannot share the task update's scatter batch.
"""

import json
import os
from collections import defaultdict
from pprint import pprint

import numpy as np
import ray
import torch
from tqdm import tqdm

import verl.utils.torch_functional as verl_F
from verl import DataProto
from verl.protocol import pad_dataproto_to_divisor, unpad_dataproto
from verl.trainer.ppo.core_algos import agg_loss
from verl.trainer.ppo.ray_trainer import (
    _timer,
    apply_invalid_action_penalty,
    apply_kl_penalty,
    compute_advantage,
    compute_response_mask,
)
from verl.trainer.ppo.reward import compute_reward, compute_reward_async
from verl.trainer.ppo.grsd_utils import compute_grsd_turn_advantage
from verl.trainer.ppo.grsd_ray_trainer import GRSDRayTrainer, build_teacher_batch_with_text
from verl.trainer.ppo.grsd_reflect_prompts import (
    REFLECT_SYSTEM,
    PRIOR_SYSTEM,
    build_reflect_user_content,
    build_prior_user_content,
)
from verl.trainer.ppo.grsd_reflect_utils import (
    ReflectionJudge,
    compute_group_normalized_advantage,
    compute_grsd_token_advantage,
    format_trajectory,
)
from verl.utils.metric import reduce_metrics
from verl.utils.model import compute_position_id_with_mask
from verl.trainer.ppo.metric_utils import (
    compute_data_metrics,
    compute_throughout_metrics,
    compute_timing_metrics,
)

from agent_system.multi_turn_rollout import adjust_batch


class GRSDReflectRayTrainer(GRSDRayTrainer):
    """Policy-native GRSD: trainable reflection (Stage A) + stop-grad prior (Stage B)."""

    def __init__(self, *args, reflection_judge: ReflectionJudge = None, **kwargs):
        super().__init__(*args, **kwargs)
        self.reflection_judge = reflection_judge
        grsd_cfg = self.config.algorithm.get("grsd", {})
        self.judge_enabled = grsd_cfg.get("judge_enabled", True)
        if self.judge_enabled and self.reflection_judge is None:
            raise ValueError("judge_enabled=True requires a ReflectionJudge")
        # alpha in L = L_task + alpha * L_ref (paper Eq. total_loss).
        self.reflect_loss_coef = grsd_cfg.get("reflect_loss_coef", 0.1)
        # sample reflections/prior with the rollout temperature (diversity for GRPO).
        self.reflect_do_sample = grsd_cfg.get("reflect_do_sample", True)
        # prompt-shaping limits for the reflection/judge trajectory text.
        self.reflect_max_turns = grsd_cfg.get("reflect_max_turns", 50)
        self.reflect_max_chars_per_obs = grsd_cfg.get("reflect_max_chars_per_obs", 1200)
        # Stage-A reflection and Stage-B prior generation can use a longer
        # context than normal task prompts. The vLLM max_model_len must cover
        # this prompt budget plus the generated response.
        self.reflect_max_prompt_length = int(
            grsd_cfg.get("reflect_max_prompt_length", self.config.data.max_prompt_length)
        )
        rollout_max_model_len = self.config.actor_rollout_ref.rollout.get("max_model_len", None)
        if rollout_max_model_len is not None:
            required_model_len = self.reflect_max_prompt_length + self.config.data.max_response_length
            if int(rollout_max_model_len) < required_model_len:
                raise ValueError(
                    "actor_rollout_ref.rollout.max_model_len must be at least "
                    "algorithm.grsd.reflect_max_prompt_length + data.max_response_length "
                    f"({required_model_len}), got {rollout_max_model_len}"
                )
        # Sampling dump: every `reflect_sample_freq` steps, persist one sampled
        # prompt's Stage-A reflections + Stage-B prior to jsonl for inspection.
        # Default dir lives under the checkpoint dir; None/"" disables dumping.
        self.reflect_sample_freq = int(grsd_cfg.get("reflect_sample_freq", 5))
        default_sample_dir = os.path.join(self.config.trainer.default_local_dir, "reflect_samples")
        self.reflect_sample_dir = grsd_cfg.get("reflect_sample_dir", default_sample_dir)

        # Ablation: modulation granularity. "turn" (default) gives every token in
        # a turn the same coefficient (compute_grsd_turn_advantage); "token" gives
        # each token its own coefficient (compute_grsd_token_advantage).
        self.grsd_modulation_level = grsd_cfg.get("modulation_level", "turn")
        assert self.grsd_modulation_level in ("turn", "token"), (
            f"algorithm.grsd.modulation_level must be 'turn' or 'token', "
            f"got {self.grsd_modulation_level!r}"
        )
        # For token-level modulation: whether to keep the group mean-abs
        # normalization ("group") or drop it entirely ("none", RLSD-style;
        # scale then controlled only by the g_hat_max clamp). Ignored for "turn".
        self.grsd_token_norm = grsd_cfg.get("token_norm", "group")
        assert self.grsd_token_norm in ("group", "none"), (
            f"algorithm.grsd.token_norm must be 'group' or 'none', "
            f"got {self.grsd_token_norm!r}"
        )

    # ------------------------------------------------------------------ #
    # Policy generation helpers (Stage A reflections + Stage B prior)
    # ------------------------------------------------------------------ #
    def _chat_prompt(self, system: str, user: str) -> str:
        chat = [
            {"role": "system", "content": system},
            {"role": "user", "content": user},
        ]
        kwargs = self.config.data.get("apply_chat_template_kwargs", {})
        try:
            from omegaconf import OmegaConf

            if OmegaConf.is_config(kwargs):
                kwargs = OmegaConf.to_container(kwargs, resolve=True)
        except Exception:
            pass
        return self.tokenizer.apply_chat_template(
            chat, add_generation_prompt=True, tokenize=False, **(kwargs or {})
        )

    def _texts_to_gen_batch(self, prompt_texts) -> DataProto:
        """Tokenize a list of chat-templated prompt strings into a gen batch.

        Uses LEFT truncation regardless of the task's data.truncation setting,
        because reflection prompts embed a full trajectory and may exceed
        max_prompt_length (task truncation is often 'error').
        """
        from verl.utils.dataset.rl_dataset import collate_fn

        max_prompt_length = self.reflect_max_prompt_length
        samples = []
        for text in prompt_texts:
            input_ids, attention_mask = verl_F.tokenize_and_postprocess_data(
                prompt=text,
                tokenizer=self.tokenizer,
                max_length=max_prompt_length,
                pad_token_id=self.tokenizer.pad_token_id,
                left_pad=True,
                truncation="left",
            )
            position_ids = compute_position_id_with_mask(attention_mask)
            raw_prompt_ids = self.tokenizer.encode(text, add_special_tokens=False)
            if len(raw_prompt_ids) > max_prompt_length:
                raw_prompt_ids = raw_prompt_ids[-max_prompt_length:]
            samples.append({
                "input_ids": input_ids[0],
                "attention_mask": attention_mask[0],
                "position_ids": position_ids[0],
                "raw_prompt_ids": raw_prompt_ids,
            })
        return DataProto.from_single_dict(data=collate_fn(samples))

    def _generate_with_policy(self, prompt_texts, do_sample=True):
        """Run the policy rollout engine on prompt_texts; returns unpadded DataProto."""
        if not prompt_texts:
            return None
        gen_batch = self._texts_to_gen_batch(prompt_texts)
        gen_batch.meta_info = {"do_sample": do_sample, "validate": False}
        padded, pad_size = pad_dataproto_to_divisor(gen_batch, self.actor_rollout_wg.world_size)
        out_padded = self.actor_rollout_wg.generate_sequences(padded)
        return unpad_dataproto(out_padded, pad_size=pad_size)

    # ------------------------------------------------------------------ #
    # Stage A + judge + Stage B (policy-native, replaces external API)
    # ------------------------------------------------------------------ #
    def _group_trajectories(self, batch: DataProto):
        """Group flattened turn rows by uid -> traj_uid -> ordered turns.

        Returns (uid_order, traj_list) where traj_list is a deterministic list of
        per-trajectory dicts: {uid, traj_uid, success, task_text, turns}.
        """
        bs = batch.batch["responses"].size(0)
        uids = batch.non_tensor_batch["uid"]
        traj_uids = batch.non_tensor_batch["traj_uid"]
        turn_steps = batch.non_tensor_batch.get("turn_step", np.zeros(bs, dtype=object))
        episode_rewards = batch.non_tensor_batch.get("episode_rewards", np.zeros(bs, dtype=object))

        group = {}
        traj_reward = {}
        traj_order = {}
        uid_order = []
        for i in range(bs):
            uid = uids[i]
            tj = traj_uids[i]
            obs, action = self._decode_turn(batch, i)
            group.setdefault(uid, {}).setdefault(tj, []).append((int(turn_steps[i]), obs, action))
            traj_reward[(uid, tj)] = float(episode_rewards[i])
            if uid not in traj_order:
                traj_order[uid] = []
                uid_order.append(uid)
            if tj not in traj_order[uid]:
                traj_order[uid].append(tj)

        def _task_text(uid):
            tj0 = traj_order[uid][0]
            turns = sorted(group[uid][tj0], key=lambda x: x[0])
            return turns[0][1] if turns else ""

        traj_list = []
        for uid in uid_order:
            for tj in traj_order[uid]:
                turns_sorted = [
                    {"obs": o, "action": a}
                    for (_, o, a) in sorted(group[uid][tj], key=lambda x: x[0])
                ]
                traj_list.append({
                    "uid": uid,
                    "traj_uid": tj,
                    "success": traj_reward[(uid, tj)] > 0.0,
                    "task_text": _task_text(uid),
                    "turns": turns_sorted,
                })
        return uid_order, traj_list

    def _reflect_and_build_priors(self, batch: DataProto):
        """Policy-native Stage A + rubric judge + Stage B.

        Returns:
            row_skill_text: list[str] length bs (z_x per row, "" if m_x=0).
            row_valid: np.ndarray[bool] length bs (m_x per row).
            reflect_pack: dict with the Stage-A generation output + Norm_G
                          advantages, used to build the reflection train batch,
                          or None if no reflections were produced.
            metrics: dict.
        """
        bs = batch.batch["responses"].size(0)
        uids = batch.non_tensor_batch["uid"]
        uid_order, traj_list = self._group_trajectories(batch)
        uid_to_int = {u: k for k, u in enumerate(uid_order)}

        # ---- Stage A: generate one reflection per trajectory with the policy. ----
        reflect_prompts = []
        for tj in traj_list:
            traj_text = format_trajectory(tj["turns"], self.reflect_max_turns, self.reflect_max_chars_per_obs)
            user = build_reflect_user_content(tj["task_text"], traj_text, tj["success"])
            reflect_prompts.append(self._chat_prompt(REFLECT_SYSTEM, user))

        reflect_out = self._generate_with_policy(reflect_prompts, do_sample=self.reflect_do_sample)
        reflection_texts = self.tokenizer.batch_decode(
            reflect_out.batch["responses"], skip_special_tokens=True
        )

        # ---- Judge each reflection -> discrete {0,1,2,3}; Norm_G advantage. ----
        # Judge calls are network-bound and independent, so score the whole group
        # concurrently (the API supports concurrency). Order is preserved.
        scores = np.zeros(len(traj_list), dtype=np.float64)
        valid = np.zeros(len(traj_list), dtype=bool)
        ref_group_ids = np.zeros(len(traj_list), dtype=np.int64)
        for k, tj in enumerate(traj_list):
            ref_group_ids[k] = uid_to_int[tj["uid"]]

        n_judge_fail = 0
        if self.judge_enabled:
            judge_items = [
                {
                    "task_text": tj["task_text"],
                    "turns": tj["turns"],
                    "reflection_text": reflection_texts[k],
                    "success": tj["success"],
                }
                for k, tj in enumerate(traj_list)
            ]
            judge_scores = self.reflection_judge.score_batch(judge_items)
            for k, s in enumerate(judge_scores):
                if s is None:
                    n_judge_fail += 1
                else:
                    scores[k] = float(s)
                    valid[k] = True
            ref_adv = compute_group_normalized_advantage(scores, ref_group_ids, valid)
        else:
            # With no external rewards there is no reflection-only optimizer pass.
            ref_adv = np.zeros(len(traj_list), dtype=np.float32)

        # ---- Stage B: contrastive prior z_x per group (stop-grad policy snapshot). ----
        uid_pos = defaultdict(list)
        uid_neg = defaultdict(list)
        uid_task_text = {}
        for k, tj in enumerate(traj_list):
            uid_task_text[tj["uid"]] = tj["task_text"]
            (uid_pos if tj["success"] else uid_neg)[tj["uid"]].append(reflection_texts[k])

        prior_uids = [u for u in uid_order if uid_pos[u] and uid_neg[u]]
        prior_prompts = [
            self._chat_prompt(
                PRIOR_SYSTEM, build_prior_user_content(uid_task_text[u], uid_pos[u], uid_neg[u])
            )
            for u in prior_uids
        ]
        uid_to_prior = {}
        if prior_prompts:
            prior_out = self._generate_with_policy(prior_prompts, do_sample=self.reflect_do_sample)
            prior_texts = self.tokenizer.batch_decode(
                prior_out.batch["responses"], skip_special_tokens=True
            )
            for u, z in zip(prior_uids, prior_texts):
                if z and z.strip():
                    uid_to_prior[u] = z.strip()

        row_skill_text = []
        row_valid = np.zeros(bs, dtype=bool)
        for i in range(bs):
            z = uid_to_prior.get(uids[i])
            if z:
                row_skill_text.append(z)
                row_valid[i] = True
            else:
                row_skill_text.append("")
                row_valid[i] = False

        # ---- Periodic sampling dump (Stage A reflections + Stage B prior). ----
        self._maybe_dump_reflect_sample(
            traj_list=traj_list,
            reflection_texts=reflection_texts,
            scores=scores,
            valid=valid,
            uid_order=uid_order,
            uid_to_prior=uid_to_prior,
        )

        reflect_pack = None
        if self.judge_enabled:
            reflect_pack = {
                "reflect_out": reflect_out,
                "ref_adv": ref_adv,
                "valid": valid,
            }
        judge_call_count = self.reflection_judge.call_count if self.reflection_judge is not None else 0
        judge_fail_count = self.reflection_judge.fail_count if self.reflection_judge is not None else 0
        metrics = {
            "grsd_reflect/n_trajectories": float(len(traj_list)),
            "grsd_reflect/n_valid_groups": float(len(uid_to_prior)),
            "grsd_reflect/judge_enabled": float(self.judge_enabled),
            "grsd_reflect/judge_fail_ratio": float(n_judge_fail) / max(1, len(traj_list)),
            "grsd_reflect/reflect_reward_mean": float(scores[valid].mean()) if valid.any() else 0.0,
            "grsd_reflect/judge_call_count": float(judge_call_count),
            "grsd_reflect/judge_fail_count": float(judge_fail_count),
        }
        return row_skill_text, row_valid, reflect_pack, metrics

    def _maybe_dump_reflect_sample(
        self, traj_list, reflection_texts, scores, valid, uid_order, uid_to_prior
    ):
        """Every reflect_sample_freq steps, dump ONE sampled prompt's reflection
        artifacts to jsonl: all Stage-A per-rollout reflections for that prompt
        plus the Stage-B distilled privileged prior. No-op if disabled.
        """
        if not self.reflect_sample_dir or self.reflect_sample_freq <= 0:
            return
        if self.global_steps % self.reflect_sample_freq != 0:
            return

        # Pick one prompt (uid) to sample. Prefer a valid group (both success &
        # failure present -> a Stage-B prior exists); otherwise fall back to the
        # first uid so we still capture Stage-A reflections.
        chosen_uid = next((u for u in uid_order if u in uid_to_prior), None)
        if chosen_uid is None:
            chosen_uid = uid_order[0] if uid_order else None
        if chosen_uid is None:
            return

        stage_a = []
        task_text = ""
        for k, tj in enumerate(traj_list):
            if tj["uid"] != chosen_uid:
                continue
            task_text = tj["task_text"]
            stage_a.append({
                "traj_uid": str(tj["traj_uid"]),
                "success": bool(tj["success"]),
                "judge_score": float(scores[k]) if valid[k] else None,
                "judge_valid": bool(valid[k]),
                "reflection": reflection_texts[k],
            })

        record = {
            "global_step": int(self.global_steps),
            "uid": str(chosen_uid),
            "task_text": task_text,
            "n_rollouts": len(stage_a),
            "stage_a_reflections": stage_a,
            "stage_b_prior": uid_to_prior.get(chosen_uid),
            "stage_b_has_prior": chosen_uid in uid_to_prior,
        }

        try:
            os.makedirs(self.reflect_sample_dir, exist_ok=True)
            out_path = os.path.join(self.reflect_sample_dir, "reflect_samples.jsonl")
            with open(out_path, "a", encoding="utf-8") as f:
                f.write(json.dumps(record, ensure_ascii=False) + "\n")
            print(
                f"[GRSD-Reflect] dumped reflection sample (step={self.global_steps}, "
                f"uid={chosen_uid}, n_rollouts={len(stage_a)}, "
                f"has_prior={chosen_uid in uid_to_prior}) -> {out_path}"
            )
        except Exception as e:  # noqa: BLE001 - dumping must never crash training
            print(f"[GRSD-Reflect] reflection sample dump failed: {type(e).__name__}: {e}")

    def _build_reflect_train_batch(self, reflect_pack) -> DataProto:
        """Attach recomputed old_log_probs + Norm_G advantages to the Stage-A rollout.

        Returns a DataProto ready for update_reflect_actor, or None if empty.
        """
        if reflect_pack is None:
            return None
        reflect_out = reflect_pack["reflect_out"]
        if reflect_out is None:
            return None
        ref_adv = reflect_pack["ref_adv"]

        # Recompute reflection old_log_probs with the actor (pad->compute->unpad).
        padded, pad_size = pad_dataproto_to_divisor(reflect_out, self.actor_rollout_wg.world_size)
        lp = self.actor_rollout_wg.compute_log_prob(padded)
        lp = unpad_dataproto(lp, pad_size=pad_size)
        reflect_out.batch["old_log_probs"] = lp.batch["old_log_probs"]

        response_length = reflect_out.batch["responses"].size(1)
        response_mask = reflect_out.batch["attention_mask"][:, -response_length:]
        adv = torch.as_tensor(ref_adv, dtype=torch.float32).unsqueeze(-1)  # (n,1)
        reflect_out.batch["advantages"] = adv * response_mask
        return reflect_out

    # ------------------------------------------------------------------ #
    # fit(): base GRSD loop + policy-native prior + reflection update pass
    # ------------------------------------------------------------------ #
    def fit(self):
        from omegaconf import OmegaConf
        from verl.utils.tracking import Tracking

        logger = Tracking(
            project_name=self.config.trainer.project_name,
            experiment_name=self.config.trainer.experiment_name,
            default_backend=self.config.trainer.logger,
            config=OmegaConf.to_container(self.config, resolve=True),
        )

        self.global_steps = 0
        self._load_checkpoint()

        if self.val_reward_fn is not None and self.config.trainer.get("val_before_train", True):
            val_metrics = self._validate()
            assert val_metrics, f"{val_metrics=}"
            pprint(f"Initial validation metrics: {val_metrics}")
            logger.log(data=val_metrics, step=self.global_steps)
            if self.config.trainer.get("val_only", False):
                return

        progress_bar = tqdm(total=self.total_training_steps, initial=self.global_steps, desc="GRSD-Reflect Training")
        self.global_steps += 1
        last_val_metrics = None

        for epoch in range(self.config.trainer.total_epochs):
            for batch_dict in self.train_dataloader:
                metrics = {}
                timing_raw = {}
                batch: DataProto = DataProto.from_single_dict(batch_dict)

                batch_keys_to_pop = ["input_ids", "attention_mask", "position_ids"]
                non_tensor_batch_keys_to_pop = ["raw_prompt_ids", "data_source"]
                if "multi_modal_data" in batch.non_tensor_batch:
                    non_tensor_batch_keys_to_pop.append("multi_modal_data")
                if "raw_prompt" in batch.non_tensor_batch:
                    non_tensor_batch_keys_to_pop.append("raw_prompt")
                if "tools_kwargs" in batch.non_tensor_batch:
                    non_tensor_batch_keys_to_pop.append("tools_kwargs")
                if "env_kwargs" in batch.non_tensor_batch:
                    non_tensor_batch_keys_to_pop.append("env_kwargs")
                gen_batch = batch.pop(
                    batch_keys=batch_keys_to_pop,
                    non_tensor_batch_keys=non_tensor_batch_keys_to_pop,
                )

                is_last_step = self.global_steps >= self.total_training_steps

                with _timer("step", timing_raw):
                    with _timer("gen", timing_raw):
                        gen_batch_output = self.traj_collector.multi_turn_loop(
                            gen_batch=gen_batch,
                            actor_rollout_wg=self.actor_rollout_wg,
                            envs=self.envs,
                            is_train=True,
                        )

                    del batch
                    batch = gen_batch_output

                    batch = adjust_batch(self.config, batch)
                    batch.batch["response_mask"] = compute_response_mask(batch)

                    if self.config.trainer.balance_batch:
                        self._balance_batch(batch, metrics=metrics)

                    batch.meta_info["global_token_num"] = torch.sum(batch.batch["attention_mask"], dim=-1).tolist()

                    with _timer("reward", timing_raw):
                        if self.use_rm:
                            reward_tensor = self.rm_wg.compute_rm_score(batch)
                            batch = batch.union(reward_tensor)

                        if self.config.reward_model.launch_reward_fn_async:
                            future_reward = compute_reward_async.remote(batch, self.config, self.tokenizer)
                        else:
                            reward_tensor, reward_extra_infos_dict = compute_reward(batch, self.reward_fn)

                    with _timer("old_log_prob", timing_raw):
                        old_log_prob = self.actor_rollout_wg.compute_log_prob(batch)
                        entropys = old_log_prob.batch["entropys"]
                        response_masks = batch.batch["response_mask"]
                        loss_agg_mode = self.config.actor_rollout_ref.actor.loss_agg_mode
                        entropy_loss = agg_loss(loss_mat=entropys, loss_mask=response_masks, loss_agg_mode=loss_agg_mode)
                        old_log_prob_metrics = {"actor/entropy_loss": entropy_loss.detach().item()}
                        metrics.update(old_log_prob_metrics)
                        old_log_prob.batch.pop("entropys")
                        batch = batch.union(old_log_prob)

                    # ---- GRSD-Reflect: policy-native Stage A + judge + Stage B ----
                    with _timer("grsd_reflect_construct", timing_raw):
                        row_skill_text, row_valid, reflect_pack, reflect_metrics = \
                            self._reflect_and_build_priors(batch)
                        metrics.update(reflect_metrics)

                    # ---- Build the reflection train batch (Stage A tokens + A_ref) ----
                    with _timer("grsd_reflect_logprob", timing_raw):
                        reflect_train_batch = self._build_reflect_train_batch(reflect_pack)

                    # ---- Teacher forward with per-row prior z_x (stop-grad text) ----
                    with _timer("teacher_forward", timing_raw):
                        teacher_log_probs = self._compute_teacher_log_probs_with_priors(batch, row_skill_text)
                        batch.batch["teacher_log_probs"] = teacher_log_probs

                    if self.use_reference_policy:
                        with _timer("ref", timing_raw):
                            if not self.ref_in_actor:
                                ref_log_prob = self.ref_policy_wg.compute_ref_log_prob(batch)
                            else:
                                ref_log_prob = self.actor_rollout_wg.compute_ref_log_prob(batch)
                            batch = batch.union(ref_log_prob)

                    if self.use_critic:
                        with _timer("values", timing_raw):
                            values = self.critic_wg.compute_values(batch)
                            batch = batch.union(values)

                    with _timer("adv", timing_raw):
                        reward_extra_infos_dict: dict[str, list]
                        if self.config.reward_model.launch_reward_fn_async:
                            reward_tensor, reward_extra_infos_dict = ray.get(future_reward)
                        batch.batch["token_level_scores"] = reward_tensor

                        if reward_extra_infos_dict:
                            batch.non_tensor_batch.update({k: np.array(v) for k, v in reward_extra_infos_dict.items()})

                        if self.config.actor_rollout_ref.actor.get("use_invalid_action_penalty", True):
                            batch, invalid_metrics = apply_invalid_action_penalty(
                                batch,
                                invalid_action_penalty_coef=self.config.actor_rollout_ref.actor.invalid_action_penalty_coef,
                            )
                            metrics.update(invalid_metrics)

                        if self.config.algorithm.use_kl_in_reward:
                            batch, kl_metrics = apply_kl_penalty(batch, kl_ctrl=self.kl_ctrl_in_reward, kl_penalty=self.config.algorithm.kl_penalty)
                            metrics.update(kl_metrics)
                        else:
                            batch.batch["token_level_rewards"] = batch.batch["token_level_scores"]

                        norm_adv_by_std_in_grpo = self.config.algorithm.get("norm_adv_by_std_in_grpo", True)
                        batch = compute_advantage(
                            batch,
                            adv_estimator=self.config.algorithm.adv_estimator,
                            gamma=self.config.algorithm.gamma,
                            lam=self.config.algorithm.lam,
                            num_repeat=self.config.actor_rollout_ref.rollout.n,
                            norm_adv_by_std_in_grpo=norm_adv_by_std_in_grpo,
                            multi_turn=self.config.actor_rollout_ref.rollout.multi_turn.enable,
                            use_pf_ppo=self.config.algorithm.use_pf_ppo,
                            pf_ppo_reweight_method=self.config.algorithm.pf_ppo.reweight_method,
                            pf_ppo_weight_pow=self.config.algorithm.pf_ppo.weight_pow,
                            step_advantage_w=self.config.algorithm.gigpo.step_advantage_w,
                            gigpo_mode=self.config.algorithm.gigpo.mode,
                            gigpo_enable_similarity=self.config.algorithm.gigpo.enable_similarity,
                            gigpo_similarity_thresh=self.config.algorithm.gigpo.similarity_thresh,
                        )

                        # ---- GRSD: bidirectional turn-level advantage modulation ----
                        seq_advantages = batch.batch["advantages"]
                        student_log_probs = batch.batch["old_log_probs"]
                        teacher_lp = batch.batch["teacher_log_probs"]
                        response_mask = batch.batch["response_mask"]
                        traj_index = batch.non_tensor_batch["traj_uid"]
                        current_lambda = self._get_grsd_lambda(self.global_steps)

                        uids = batch.non_tensor_batch["uid"]
                        uid_list = list(dict.fromkeys(uids))
                        uid_to_int = {u: i for i, u in enumerate(uid_list)}
                        uid_index = np.array([uid_to_int[u] for u in uids], dtype=np.int64)

                        is_token = self.grsd_modulation_level == "token"
                        mod_kwargs = dict(
                            seq_advantages=seq_advantages,
                            student_log_probs=student_log_probs,
                            teacher_log_probs=teacher_lp,
                            response_mask=response_mask,
                            traj_index=traj_index,
                            valid_mask=row_valid,
                            uid_index=uid_index,
                            grsd_lambda=current_lambda,
                            eta=self.grsd_eta,
                            g_hat_max=self.grsd_g_hat_max,
                        )
                        if is_token:
                            mod_kwargs["token_norm"] = self.grsd_token_norm
                        token_advantages, grsd_metrics = (
                            compute_grsd_token_advantage if is_token
                            else compute_grsd_turn_advantage
                        )(**mod_kwargs)
                        batch.batch["advantages"] = token_advantages
                        grsd_metrics["grsd/lambda"] = current_lambda
                        metrics.update(grsd_metrics)

                        batch.batch.pop("teacher_log_probs", None)

                    if self.use_critic:
                        with _timer("update_critic", timing_raw):
                            critic_output = self.critic_wg.update_critic(batch)
                        critic_output_metrics = reduce_metrics(critic_output.meta_info["metrics"])
                        metrics.update(critic_output_metrics)

                    if self.config.trainer.critic_warmup <= self.global_steps:
                        with _timer("update_actor", timing_raw):
                            batch.meta_info["multi_turn"] = self.config.actor_rollout_ref.rollout.multi_turn.enable
                            actor_output = self.actor_rollout_wg.update_actor(batch)
                        actor_output_metrics = reduce_metrics(actor_output.meta_info["metrics"])
                        metrics.update(actor_output_metrics)

                        # ---- Reflection GRPO update (separate alpha-weighted pass) ----
                        if reflect_train_batch is not None:
                            with _timer("update_reflect_actor", timing_raw):
                                reflect_metrics2 = self._update_reflect(reflect_train_batch)
                            metrics.update(reflect_metrics2)

                    rollout_data_dir = self.config.trainer.get("rollout_data_dir", None)
                    if rollout_data_dir:
                        with _timer("dump_rollout_generations", timing_raw):
                            inputs = self.tokenizer.batch_decode(batch.batch["prompts"], skip_special_tokens=True)
                            outputs = self.tokenizer.batch_decode(batch.batch["responses"], skip_special_tokens=True)
                            scores = batch.batch["token_level_scores"].sum(-1).cpu().tolist()
                            self._dump_generations(
                                inputs=inputs,
                                outputs=outputs,
                                scores=scores,
                                reward_extra_infos_dict=reward_extra_infos_dict,
                                dump_path=rollout_data_dir,
                            )

                    test_start_step = self.config.trainer.get("test_start_step", 0)
                    if self.val_reward_fn is not None and self.config.trainer.test_freq > 0 and (is_last_step or (self.global_steps >= test_start_step and self.global_steps % self.config.trainer.test_freq == 0)):
                        with _timer("testing", timing_raw):
                            val_metrics: dict = self._validate()
                            if is_last_step:
                                last_val_metrics = val_metrics
                        metrics.update(val_metrics)

                    if self.config.trainer.save_freq > 0 and (is_last_step or self.global_steps % self.config.trainer.save_freq == 0):
                        with _timer("save_checkpoint", timing_raw):
                            self._save_checkpoint()

                metrics.update({
                    "training/global_step": self.global_steps,
                    "training/epoch": epoch,
                })
                metrics.update(compute_data_metrics(batch=batch, use_critic=self.use_critic))
                metrics.update(compute_timing_metrics(batch=batch, timing_raw=timing_raw))
                n_gpus = self.resource_pool_manager.get_n_gpus()
                metrics.update(compute_throughout_metrics(batch=batch, timing_raw=timing_raw, n_gpus=n_gpus))

                logger.log(data=metrics, step=self.global_steps)

                progress_bar.update(1)
                self.global_steps += 1
                if is_last_step:
                    pprint(f"Final validation metrics: {last_val_metrics}")
                    progress_bar.close()
                    return

    def _update_reflect(self, reflect_train_batch: DataProto) -> dict:
        """Run the alpha-weighted reflection GRPO optimizer pass on padded tokens."""
        padded, pad_size = pad_dataproto_to_divisor(reflect_train_batch, self.actor_rollout_wg.world_size)
        if pad_size > 0:
            # zero-out advantages of padded (duplicated) rows so they add no gradient.
            orig = padded.batch["advantages"].size(0) - pad_size
            padded.batch["advantages"][orig:] = 0.0
        padded.meta_info["temperature"] = self.config.actor_rollout_ref.rollout.temperature
        padded.meta_info["reflect_loss_coef"] = self.reflect_loss_coef
        out = self.actor_rollout_wg.update_reflect_actor(padded)
        return reduce_metrics(out.meta_info["metrics"])
